/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.arduinojava;

import javax.swing.JFrame;
import com.panamahitek.*;
import javax.swing.JOptionPane;
import jssc.SerialPortException;
/**
 *
 * @author Hp
 */
public class Display extends javax.swing.JDialog {

    /**
     * Creates new form Display
     */
    public int estadoDisplayHijo;
    public PanamaHitek_Arduino arduinoHijo;
    public Display(java.awt.Frame parent, boolean modal, int estadoDisplay, PanamaHitek_Arduino arduino) {
        super(parent, modal);
        initComponents();
        estadoDisplayHijo = estadoDisplay;
        arduinoHijo = arduino;
        if(estadoDisplay==1){
            btnEncenderDisplay.setEnabled(false);
            btnApagarDisplay.setEnabled(true);
             
        }else{
            btnApagarDisplay.setEnabled(false);
            btnEncenderDisplay.setEnabled(true);
        }
    }

    private Display(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnApagarDisplay = new javax.swing.JButton();
        btnEncenderDisplay = new javax.swing.JButton();
        txtTextoDisplay = new javax.swing.JTextField(16);
        btnMostrarDisplay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuracion de Display");

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Exit_24.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Display");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setText("* Limpia los mensajes actuales del display");

        jLabel3.setText("* Iluminacion de Fondo (backligth()) ");

        btnApagarDisplay.setText("Apagar");
        btnApagarDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarDisplayActionPerformed(evt);
            }
        });

        btnEncenderDisplay.setText("Encender");
        btnEncenderDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderDisplayActionPerformed(evt);
            }
        });

        txtTextoDisplay.setText("Escriba texto");
        txtTextoDisplay.setMaximumSize(new java.awt.Dimension(16, 16));
        txtTextoDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTextoDisplayKeyPressed(evt);
            }
        });

        btnMostrarDisplay.setText("Mostrar en Display");
        btnMostrarDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTextoDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEncenderDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnApagarDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMostrarDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEncenderDisplay)
                    .addComponent(btnApagarDisplay)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTextoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarDisplay))
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApagarDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarDisplayActionPerformed
        // TODO add your handling code here:
        btnEncenderDisplay.setEnabled(true);
        btnApagarDisplay.setEnabled(false);
        estadoDisplayHijo = 0;
        try { 
              arduinoHijo.sendData("dispapagarDisplay");
            } catch (ArduinoException ex) {
                JOptionPane.showConfirmDialog(null, ex, "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            } catch (SerialPortException ex) {
                JOptionPane.showConfirmDialog(null, ex, "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnApagarDisplayActionPerformed

    private void btnEncenderDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderDisplayActionPerformed
        // TODO add your handling code here:
        btnEncenderDisplay.setEnabled(false);
        btnApagarDisplay.setEnabled(true);
        estadoDisplayHijo = 1;
        try {                
                    arduinoHijo.sendData("dispencederDisplay");
            } catch (ArduinoException ex) {
                JOptionPane.showConfirmDialog(null, ex, "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            } catch (SerialPortException ex) {
                JOptionPane.showConfirmDialog(null, ex, "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            }
        
    }//GEN-LAST:event_btnEncenderDisplayActionPerformed

    private void txtTextoDisplayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTextoDisplayKeyPressed
        // TODO add your handling code here:
        if(txtTextoDisplay.getText().length()>16){
            txtTextoDisplay.setText(txtTextoDisplay.getText().substring(0,16));
        }
    }//GEN-LAST:event_txtTextoDisplayKeyPressed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
	dispose(); 
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        
            try {                
                    arduinoHijo.sendData("displimpiarDisplay");
            } catch (ArduinoException ex) {
                JOptionPane.showConfirmDialog(null, ex, "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            } catch (SerialPortException ex) {
                JOptionPane.showConfirmDialog(null, ex, "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnMostrarDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDisplayActionPerformed
        // TODO add your handling code here:
        try {                
                    arduinoHijo.sendData("disp"+this.txtTextoDisplay.getText());
            } catch (ArduinoException ex) {
                JOptionPane.showConfirmDialog(null, ex, "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            } catch (SerialPortException ex) {
                JOptionPane.showConfirmDialog(null, ex, "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            }
        
    }//GEN-LAST:event_btnMostrarDisplayActionPerformed

    /**
     *
     */
    public int getEstadoDisplay(){
        return estadoDisplayHijo;
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Display dialog = new Display(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagarDisplay;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEncenderDisplay;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrarDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtTextoDisplay;
    // End of variables declaration//GEN-END:variables
}
